### ISSUE TITLE
Bug on Neutral Faction Script

### ISSUE THREAD

**Issue by Mouti37** [Goinza/Plugins-for-SRPG-Studio#4]
Hi, I keep getting the same error message when trying to implement the Neutral Faction script into my SRPG project. I tried making an empty test map it check if there were any script conflicts but the same error persists.
![Neutral Faction Error](https://user-images.githubusercontent.com/90284567/132406492-fa7dcbb2-50bf-46ef-acf3-81983d55a542.jpg)
I basically have no programming knowledge so have no idea how to fix this. It would be a fantastic script for my project if I can get it working and I appreciate the time and effort that goes into making these scripts. So any idea what's wrong?

**Comment by Goinza** [comment]
I can't recreate the problem. It is possible that it may not be a bug, but instead it could be a problem in the configuration of the custom parameters, graphical assets, etc.

Could you provide more information of the scenario? Screenshots of all the custom parameters and all the configuration you did so far would be useful.

Also, if it is possible, try to remove all plugins except the Neutral Faction plugin to make sure the error doesn't come from a clash with another plugin.

**Comment by Mouti37** [comment]
Okay, so I made another test map, 'Test Map2'. A completely empty map apart from the 3 units you see in the picture. The player unit, a normal enemy unit and an enemy unit with parameter {neutralFaction: true} as stated in the readme.txt. There is nothing else in the project saved as 'Test Map2', no extra graphical assets or plugins just the Neutral Faction plugin.
![Test Map2](https://user-images.githubusercontent.com/90284567/132719561-78fefd06-57b4-43b3-8010-97a64298af50.jpg)
When I Test Play the map, it goes into the Player Phase which I end, Enemy Phase where the normal enemy unit moves up the map and attacks the neutral enemy unit, this tells me the plugin is partially working as the two enemy units fight as I would expect and the battle ends without error. Then the Enemy Phase ends and the 'Neutral Phase' starts and it's right after I see the second 'Enemy Phase' popup that I get the Script Error message.
![End Result](https://user-images.githubusercontent.com/90284567/132720867-f3d505ae-32ea-4360-8de4-2ef5c0988afa.jpg)
This is how I configured the parameter on the top enemy unit:
![Custom Parameter](https://user-images.githubusercontent.com/90284567/132721023-86735016-8d28-49f5-a301-77264e168fc6.jpg)
And that was all. That's all I did. The readme says I don't need to do anything else. Unless I made an error copying over the scripts. Here's what it looks like:
![Plugin Setup](https://user-images.githubusercontent.com/90284567/132721529-8e46932e-cb46-4599-85ce-1ac92181e28d.jpg)
I may be doing this a stupid slow way but I basically looked at the Raw view of each of the Neutral Faction scripts.
Select All-->Copy-->Paste into Notepad++-->Save as type JavaScript file-->copy the exact name from the site--> Save.
I can see myself making an error here, such as saving a script with the wrong name or saving the same script twice with a different name. I can do it again to make sure it's just time consuming since there are 18 scripts including the readme file. I've done this with other plugins and it's worked fine up till now.
I can't really think of anything else I'm doing wrong. Did an update on SRPG Studio on Steam make the Plugin incompatible with the current version of SRPG Studio. That doesn't seem likely if you got it working yesterday. I'm using Windows10 OS.
Anything I'm doing wrong?

**Comment by Goinza** [comment]
Ok, this extra information surely will help in figuring out the issue.

You could try to download again the plugin, but that isn't the method you are supposed to use. I don't think that will fix the issue, but for now try to download again from this site https://goinza.github.io/srpg-plugins/plugins/neutral-faction.html

I'll let you know when I found the problem

**Comment by Mouti37** [comment]
Hi again, so, I download the plugin from your link and put it in a new test map, Test Map 3. I noticed the file sizes are slightly different from the scripts I saved through Notepad++. However despite that, I still get the same error as in the pictures above. Is it possible I need to update something on my computer? Or perhaps install Java on my computer? I'm not 100% sure so forgive my ignorance but I believe you don't need to install Java for your computer to read JavaScript or it was only needed in older browers as I remember updating Java on my computer years back.

**Comment by Goinza** [comment]
I found the solution to the bug. Turns out that if the neutral unit doesn't have its own map sprite, it crashes the game when the unit calls the moving animation. It is fixed now, you can redownload the plugin from the page and it should no longer crash.

Thank you for notifying this bug, I appreciate your help with this issue.

I closed the issue, since the bug should be gone, but if it still happens, or you find another bug from this or other of my plugins, feel free to open another issue.
