### ISSUE TITLE
Action combat arts don't work with some item types (Teleportation, Key, Rescue)

### ISSUE THREAD

**Issue by miyamadoKL** [Goinza/Plugins-for-SRPG-Studio#8]
Hello, I tried to use action combat arts to use the teleportation item, but it doesn't work properly with some item types.
It seems that it cannot select a destination after deciding a target to teleport. Also, Key items cannot select a door to open and rescue items don't work after deciding a target.

I think these behaviors are caused by `CAState.ActionTarget` , but is there a way to fix that?

**Comment by odama16020** [comment]
I'm sorry to overlooked, but "Weapons and Items as Original Data" plugin realized what I wanted to do.
So It's OK to close this issue.

**Comment by miyamadoKL** [comment]
I'm sorry to overlooked, but "Weapons and Items as Original Data" plugin realized what I wanted to do.
So It's OK to close this issue.
